services:
  backend:
    image: filipton/fkm-micro-connector:latest
    container_name: micro-connector
    network_mode: host
    build:
      dockerfile: Dockerfile
      target: backend
    volumes:
      - /run/dbus:/run/dbus:ro
      - /tmp/fkm-build:/app/firmware
      - /tmp/sock:/app/sock
    environment:
      - PORT=8080
      - FIRMWARE_DIR=/app/firmware
      - API_URL=http://localhost:5001
      - API_TOKEN=paste_your_token_here
      - RUST_LOG=none,backend=debug
      - SOCKET_PATH=/app/sock/socket.sock
      - DEV=1 #comment if you dont want to use dev build
    restart: unless-stopped
    depends_on:
      - e2e
  e2e:
    image: filipton/fkm-e2e:latest
    container_name: e2e
    build:
      dockerfile: Dockerfile
      target: e2e
    volumes:
      - /tmp/sock:/app/sock
      - ./tests.json:/app/tests.json
    environment:
      - RUST_LOG=none,e2e=debug
      - SOCKET_PATH=/app/sock/socket.sock
    restart: unless-stopped
